
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'functionCOMMA DIVIDE LPAREN MINUS NAME NUMBER PLUS RPAREN SEMICOLON TIMES\n    root : function SEMICOLON\n    \n    function : NAME LPAREN args RPAREN\n    \n    args : arg COMMA args\n    \n    args : arg\n    \n    arg : function \n        | identifier\n    \n    identifier : NAME\n    '
    
_lr_action_items = {'NAME':([0,3,10,],[2,4,4,]),'$end':([1,9,],[0,-2,]),'LPAREN':([2,4,],[3,3,]),'COMMA':([4,6,7,8,9,],[-7,10,-5,-6,-2,]),'RPAREN':([4,5,6,7,8,9,11,],[-7,9,-4,-5,-6,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,3,10,],[1,7,7,]),'args':([3,10,],[5,11,]),'arg':([3,10,],[6,6,]),'identifier':([3,10,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('root -> function SEMICOLON','root',2,'p_root','ylp.py',81),
  ('function -> NAME LPAREN args RPAREN','function',4,'p_function','ylp.py',87),
  ('args -> arg COMMA args','args',3,'p_args_recur','ylp.py',96),
  ('args -> arg','args',1,'p_args_single','ylp.py',103),
  ('arg -> function','arg',1,'p_arg','ylp.py',109),
  ('arg -> identifier','arg',1,'p_arg','ylp.py',110),
  ('identifier -> NAME','identifier',1,'p_identifier','ylp.py',116),
]
