
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHILD NEXT NUMBER\n    root : selects\n    \n    selects : select NEXT selects\n    \n    selects : select\n    \n    select : childselect\n    \n    childselect : CHILD NUMBER\n    '
    
_lr_action_items = {'CHILD':([0,6,],[5,5,]),'$end':([1,2,3,4,7,8,],[0,-1,-3,-4,-5,-2,]),'NEXT':([3,4,7,],[6,-4,-5,]),'NUMBER':([5,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'root':([0,],[1,]),'selects':([0,6,],[2,8,]),'select':([0,6,],[3,3,]),'childselect':([0,6,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root","S'",1,None,None,None),
  ('root -> selects','root',1,'p_root','selecter.py',80),
  ('selects -> select NEXT selects','selects',3,'p_selects_1','selecter.py',86),
  ('selects -> select','selects',1,'p_selects_2','selecter.py',92),
  ('select -> childselect','select',1,'p_select','selecter.py',98),
  ('childselect -> CHILD NUMBER','childselect',2,'p_childselect','selecter.py',104),
]
